aws_region = "eu-west-2"
s3_bucket = "doorfeed-prod-tfstate"
ecr_repo_name = "doorfeed-prod"
ecs_task_execution_role = "arn:aws:iam::123456789012:role/ecsTaskExecutionRoleProd"
ecr_repo_url = "123456789012.dkr.ecr.eu-west-2.amazonaws.com/doorfeed-prod"
image_tag = "latest"
