aws_region = "eu-west-2"
s3_bucket = "doorfeed-dev-tfstate"
ecr_repo_name = "doorfeed-dev"
ecs_task_execution_role = "arn:aws:iam::123456789012:role/ecsTaskExecutionRoleDev"
ecr_repo_url = "123456789012.dkr.ecr.eu-west-2.amazonaws.com/doorfeed-dev"
image_tag = "latest"
